### PR TITLE
simplify and speed up

### PR DESCRIPTION
**Pull request by neilehavens**
The original version of the script recorded timings for its execution that included sleep statements and two checks for each url. These commits remove the sleep statements and the duplicate execution. The result should be faster execution and simpler code.

### CODE REVIEW

**Comment by ozzi-** [comment]
Hi Neile
Thanks for your commits, however your code seems to break when the url's set were not yet scanned by Qualys:
```
ozzi@ubuntuvm:~/Desktop$ cat a
www.yahoo.com;www.google.com;www.rt.com
ozzi@ubuntuvm:~/Desktop$ ./consoleLabs.ssh a

1 / 3 - Scan result of www.yahoo.com
"grade": "A+",
      

2 / 3 - Scan result of www.google.com
"grade": "A",
      

3 / 3 - 
```
rt.com was not scanned recently, thus was the API was not ready to respond on the first request. Thus nothing is returned. 
Otherwise your commits make perfect sense, i am not very proficient with bash as you can see.

**Comment by ozzi-** [comment]
The problem arises in commit "simplify and speed up"
If you can change this, ill gladly accept your pull request.

**Comment by neilehavens** [comment]
Thanks for the feedback.  I'll look into the issue to see if there is a way to get bash to wait for the curl command run in a subshell ( $() ) to complete before moving on.  I'd rather go that route that re-introduce the priming hit to the api that was in the script previously.

________________________________

**Comment by ozzi-** [comment]
I am not sure if i understand you correctly. 
The curl command, even in a subshell, will finish even if the scan has not been completed. 

The API works like the following.
If the domain has to be scanned first, you receive:
`  "statusMessage": "Resolving domain names",
`
Then it transitions into:
`  "status": "IN_PROGRESS",
`
When its done and the grade has been calculated:
`  "status": "READY",
`
So some kind of polling mechanism has to be implemented, meaning you will have to initiate the scan for all domains and then poll all of them until they are done  (Its better to initiate all scans first and then come back checking for results, otherwise the runtime will be a lot longer).
You can do this in one (polling) loop, that is true, without the "primer" loop.

**Comment by neilehavens** [comment]
Thank you.  I discovered the same thing as I was working on this last night.  I had initially (and mistakenly) thought that the curl command timed out, which left $ret set to an empty string, which caused the getResult function to have no output.


I've added a polling loop, but want to do a bit more testing before I add it to my pull request.  The main question is whether it's ok to use cached results from a recent scan of the url or if we really want to initiate a new scan for each domain with each run of the script.  Any time we initiate a new scan, it dramatically slows down the script.  According to the documentation a new scan can take over a minute.  If we really want a new scan with each run of the script, then we probably should parallelize our checks of all the urls in the urlfile rather than iterating through them serially.

________________________________

**Comment by ozzi-** [comment]
In my opinion it is okay to use cached results, they aren't valid very long anyway. 
Maybe if we add a flag -f (--force-scan) which initiates a new scan, we can fulfill both use cases.
I do not quite understand where parallelization comes into play, the check if the status is "READY" is very short, thus parallelization would not give any significant (if any) performance gain.

**Comment by neilehavens** [comment]
You're right, the check for "READY" or "ERROR" status is quick.  However, if the status is not one of these, we continue to poll every 5 seconds, possibly up to a minute.  Suppose we had 5 urls to check, we could be polling for a total of 5 minutes if we polled each url one at a time.  Or, we could find a way to poll all 5 simultaneously, for a total runtime of a little over 1 minute.


I will go ahead and commit my polling changes that go through the urls one at a time.  However, I also discovered that ssllabs has developed a script very similar to this one.

https://github.com/ssllabs/ssllabs-scan/

It already has the parallel polling functionality.  The only potential downside is that it requires the go language to be installed as opposed to only needing bash and curl like your script.


________________________________

**Comment by neilehavens** [comment]
Actually, now that I look at your original script more closely, I see that you were polling the api already. My changes are probably not helpful. Sorry. Feel free to close this pull request without merging

**Comment by ozzi-** [comment]
If you can create a new pull request including only: 

do not check the length of results from getResults - d69eb11
no need to unset array values - 6a161a2
make consoleSSLlabs executable - 4be9278
fix off by one error in console output - 3b40572
simplify commandline argument checking - 665074a

Ill gladly merge.
Thanks for the help & inputs!

**Comment by neilehavens** [comment]
I think the list of useful commits is even smaller.


If I include this one, the script will never exit:

no need to unset array values - 6a161a2<https://github.com/ozzi-/consoleSSLlabs/commit/6a161a2e5466019f4959c64fae6747ec9c85eed5>


If I include this one, the script will not continue to poll the api until results are either READY or ERROR:

do not check the length of results from getResults - d69eb11<https://github.com/ozzi-/consoleSSLlabs/commit/d69eb11126e8e56e28dccfdc1eeb3084140d7bd8>

________________________________

**Pull request closed without merging**
