### PR TITLE
Fix off-by-one error in console output

### PR DESCRIPTION
**Pull request by neilehavens**
In addition to the off-by-one fix for console output, this PR also makes consoleSSLlabs executable and makes a minor simplification to command-line parsing.

### CODE REVIEW

**Comment by ozzi-** [comment]
When i run your code, nothing happens, only a blinking cursor .

**Comment by neilehavens** [comment]
Hmmm, that's strange.  Are you sure you're not running the code from the first pull request?  In this second pull request, I didn't change anything about your initialization or polling logic.  You should still immediately see "Starting scan for # URLs" followed by a . for each URL.  Just as your original script, it will continue to poll the API until results are available, possibly reporting on the URLs our of order compared to the urlfile.

________________________________

**Comment by ozzi-** [comment]
I used the current state of your fork

**Comment by neilehavens** [comment]
Did you use the pr2 branch?  Can you send the output of "git status"?

________________________________

**Comment by ozzi-** [comment]
Oh i did not see the branch. Works like a charm!

**Pull request merged**
